version: '3'mysql
services:
  mysql:
    image: mysql:latest
    container_name: mysql_ifsp
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "13306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
